### ISSUE TITLE
Portuguese (Brazil) translation

### ISSUE THREAD

**Issue by fmedinac** [Stanko/letters-from-sarajevo#6]
I'm working on translating this **masterpiece** to PT-BR 🇧🇷 and will be opening a PR soon.

**Comment by Stanko** [comment]
Thank you @fmedinac ❤️ 
You don't have to mess with source files as I made a build process complicated 🙈 just a text file would be more than enough.

EDIT: please check "alt" props on images as well, and if you need any help let me know. Also I'll need your help with the difference between Brazil-Portuguese and Portugal-Portuguese 😄
